name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Validate:
  #   runs-on: ubuntu-18.04

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: Use Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 14
  #     - name: Install Dependencies
  #       run: npm i
  #     - name: Build Code
  #       run: npm run build
  #     - name: Validate
  #       run: npm run validate
  #     - name: Coveralls
  #       uses: coverallsapp/github-action@master
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}

  Release:
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/master'
    # needs: [Validate]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm i
      # Release the Codes!!
      - name: Release!
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc && git config user.name kweh-bot && git config user.email ceciwoodwrd+choco-bot@gmail.com && npm run version -- --yes && npm run release -- --legacy-auth $NPM_AUTH --yes
